### ISSUE TITLE
Remove Google+ share button

### ISSUE THREAD

**Issue by smidley** [TheGamesDB/TheGamesDBv2#14]
The bottom of the page has a Google+ share icon that needs to be removed since that service has been retired.

![image](https://user-images.githubusercontent.com/421573/53254798-02f40500-3679-11e9-8bf9-48ade1536c7e.png)

**Comment by Zer0xFF** [comment]
solved https://github.com/TheGamesDB/TheGamesDBv2/commit/6c16969ca00f69f187c92bffdc5c5ae5f2294bcc
https://github.com/TheGamesDB/TheGamesDBv2/commit/c010bb37ccffe8baf70a8b8c5bf6bc63fc595d8c
