### ISSUE TITLE
Add region property on a game

### ISSUE THREAD

**Issue by Eric13246** [TheGamesDB/TheGamesDBv2#20]
This database is missing a really important element of game collecting, which is the region of the game. A game from different regions does not have the same market value and is essentially different in itself. I'm willing to work on this.

**Comment by Zer0xFF** [comment]
Hi Eric, thanks for your interest in taking this on.

region implementation is something we've debated and currently debating in our [discord server](https://discordapp.com/invite/Xx5f8Gx)
and someone else has suggested taking that feature on in the discord server as well, if that wasn't you, I'd recommand you join us, to prevent duplication of effort, though no common consesus have been reached.

to summerise the topics of the top of my head.
  - this will most likely end up being v2, so keeping backward compatiblity with v1
  - how do we choose which regions to support, and should sub-regions be supported as well

**Comment by Eric13246** [comment]
Hi Zer0xFF,

I wasn't aware there was a discord server for this project. I will join it to see what is happening over there and look at what is being done.

**Comment by pete-oconnell** [comment]
Regions are incorporated now - Tidying up
