### ISSUE TITLE
filter[platform] not working anymore

### ISSUE THREAD

**Issue by Hybrid512** [TheGamesDB/TheGamesDBv2#32]
Hi,

Since a few days, the filter[platform] parameter in the API doesn't work anymore.

With this request : https://api.thegamesdb.net/v1.1/Games/ByGameName?apikey=xxx&name=Batman

You get 20 results which corresponds to what you get on the TGDB website with this URL : https://thegamesdb.net/search.php?name=Batman

However, doing this should bring me only the games for the "6" platform (SNES) : 

https://api.thegamesdb.net/v1.1/Games/ByGameName?apikey=xxx&name=Batman&filter[platform]=6 

but it doesn't work.

Search on the website work however : https://thegamesdb.net/search.php?name=Batman&platform_id[]=6 and gives the expected results.

**Comment by Zer0xFF** [comment]
Thanks for bring this to my attention,

I have noted the issue and have pushed a quick fix for it to the server,
I'll keep this issue open, until i commit the fix.

**Comment by Hybrid512** [comment]
Thanks for your quick fix !
As far as I can tell, this seems to be fixed.

Best regards.

**Comment by Zer0xFF** [comment]
this has been fixed in https://github.com/TheGamesDB/TheGamesDBv2/commit/975fb00d044abbaf2e4589e6f802054502da24b1
thanks for reporting, closing the issue now
