### ISSUE TITLE
Game UIDs

### ISSUE THREAD

**Issue by pete-oconnell** [TheGamesDB/TheGamesDBv2#35]
Add support for SNES Nintendo UIDs - 

e.g 

- SNS-MW-USA
- SNS-MW-USA-1
- SNS-MW-USA-2

**Comment by plgDavid** [comment]
Its the same format for NES/Famicom as well
EG: 10-Yard Fight (Europe, USA) is "NES-TY-USA"
Cheers

**Comment by pete-oconnell** [comment]
https://github.com/TheGamesDB2/Website/issues/2
